import Head from "next/head";
// import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Running NextJS Application!</h1>
        <ul>
          <li>
            <Link href="/productportfolio">Product Portfolio</Link>
          </li>
          <li>
            <Link href="/productlist">Product List</Link>
          </li>
          <li>
            <Link href="/blog/2021/my-only-blog">My only blog</Link>
          </li>
          <li>
            <Link href="/some-random-text-for-404">404 Error (Also provides inbuilt 404 error page)</Link>
          </li>
        </ul>
      </main>
    </div>
  );
}
