import Head from "next/head";
// import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Running NextJS Application!</h1>
        <ul>
          <li>
            <Link href="/productlist">Static Route and Nested Static Routes</Link>
          </li>
          <li>
            <Link href="/productportfolio">Dynamic Route</Link>
          </li>
          <li>
            <Link href="/blog/2021/my-only-blog">Multiple Dynamic Routes</Link>
          </li>
          <li>
            <Link href="/some-random-text-for-404">
              404 Error (Also provides inbuilt 404 error page)
            </Link>
          </li>
          <li>
            <Link href="/currency">Static Generation - Pre Rendering (API fetch - Currency List)</Link>
          </li>
          <li>
            <Link href="/spacex">Server Side Rendering (API fetch - SpaceX Shuttles)</Link>
          </li>
        </ul>
      </main>
    </div>
  );
}
